### ISSUE TITLE
Unbounded Local Error on NethackTaskWrapper

### ISSUE THREAD

**Issue by saptab** [RyanNavillus/Syllabus#42]
(marl_cc) bash-4.4$  python -m tests.multiprocessing_smoke_tests
/Multi-Agent-Syllabus/syllabus/examples/task_wrappers/__init__.py:18: UserWarning: Unable to import the following nle dependencies: cv2
  warnings.warn(f"Unable to import the following nle dependencies: {e.name}")
/Multi-Agent-Syllabus/syllabus/tests/utils.py:223: UserWarning: Unable to import nle.
  warnings.warn("Unable to import nle.")
Traceback (most recent call last):
  File "/anaconda3/envs/marl_cc/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda3/envs/marl_cc/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Multi-Agent-Syllabus/tests/multiprocessing_smoke_tests.py", line 20, in <module>
    nethack_env = create_nethack_env()
  File "/Multi-Agent-Syllabus/syllabus/tests/utils.py", line 226, in create_nethack_env
    env = NethackTaskWrapper(env)
UnboundLocalError: local variable 'NethackTaskWrapper' referenced before assignment

Is the above unbounded local error due to a Python version mismatch?

**Comment by RyanNavillus** [comment]
The error is due to opencv not being installed as you see at the top of the message. We'll work on cleaning up the imports before the next release but for now you can fix this with `pip install opencv-python`
